# Dependencies
gems:                   [jekyll-gist]
markdown:               redcarpet
highlighter:            rouge

# Permalinks
permalink:              pretty

# Setup
title:                  Hyde
image:                  http://placehold.it/120x120
tagline:                'A Jekyll theme'
description:            'A variation on the <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> Jekyll theme.'
url:                    https://github.com/negomi/hyde
baseurl:                /
category_title_prefix:  'Category: '
tag_title_prefix:       'Tagged: '

author:
  name:                 'Imogen Wentworth'
  url:                  https://twitter.com/imogenwentworth

# Custom vars
version:                1.0.0

github:
  repo:                 https://github.com/negomi/hyde
